# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: azurevng
# label used for menu selection
label: Azure VNG IKE/IPSec
description: Configure IKE, IPSec and BGP for PAN-OS to connect to Azure VNG

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - cestebanez

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: azure_vgw_ip
    description: Public IP address of Azure Virtual Network Gateway
    default:
    type_hint: ip_address
  - name: azure_bgp_peer
    description: Azure Virtual Network Gateway BGP peer ip address (should be the second last ip address of your Azure gateway subnet)
    default:
    type_hint: ip_address
  - name: panos_ipsec_interface
    description: PAN-OS ethernet interface for IKE/IPsec - Ethernet interface for untrust where the Azure initiated IPSec will terminate
    default: ethernet1/1
    type_hint: dropdown
    dd_list:
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
  - name: panos_tunnel
    description: PAN-OS Tunnel inteface number - If you are using an existing tunnel interface, opt for another than tunnel.1
    default: tunnel.1
    type_hint: dropdown
    dd_list:
      - key: tunnel.1
        value: tunnel.1
      - key: tunnel.2
        value: tunnel.2
      - key: tunnel.3
        value: tunnel.3
      - key: tunnel.4
        value: tunnel.4
  - name: panos_ike_presharedkey
    description: PAN-OS IKE preshared key - This preshared key must be the same as defined on your Azure Local Network Gateway
    default: paloalto
    type_hint: text
  - name: panos_virtualrouter
    description: PAN-OS virtual router name - If you want to use another than default virtual router instance.
    default: default
    type_hint: text
  - name: panos_bgp_as
    description: PAN-OS BGP AS - Specify your local BGP AS if needed. Must match the value you configure in Azure Local Network Gateway.
    default: 65500
    type_hint: text
  - name: azure_bgp_as
    description: Azure VNG BGP AS - Specify your Azure BGP AS. Must match the value you configure in Azure Virtual Network Gateway.
    default: 65515
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: routing
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: routing.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: ikecrypto
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/ike/crypto-profiles/ike-crypto-profiles
    file: ikecrypto.xml
  - name: ikeprofile
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/ike/gateway
    file: ikeprofile.xml
  - name: ipseccrypto
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/ike/crypto-profiles/ipsec-crypto-profiles
    file: ipseccrypto.xml
  - name: ipsecprofile
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/tunnel/ipsec
    file: ipsecprofile.xml

  # ---------------------------------------------------------------------
# end of snippets section
